name: FloorIsLava
main: com.yahoo.tracebachi.FloorIsLava.FloorIsLava
version: Alpha
commands:
    floor:
        description: Use to interact with the FloorIsLava minigame.
        usage: /floor [join/leave/count/watch/wager] [wager amount]
permissions:
    FloorIsLava.staff:
        description: Gives OP level control of FloorIsLava.
        default: op
