name: FloorIsLava
main: com.gmail.tracebachi.FloorIsLava.FloorIsLavaPlugin
version: 2.2
depend: [Vault]
commands:
  floor:
    description: Main FIL command.
  mfloor:
    description: Main FIL management command.
permissions:
  FloorIsLava.Staff:
    description: Allows the user to control FIL start-stop-reload-enable-disable.
