name: FloorIsLava
main: com.gmail.tracebachi.FloorIsLava.FloorIsLavaPlugin
version: ${project.version}
authors: [Trace Bachi (BigBossZee), Jeremy Lugo (Refrigerbater)]
depend: [Vault]
commands:
  floor:
    description: Main FIL command.
  floorbooster:
    description: FIL command for arena boosters.
  mfloor:
    description: Main FIL management command.
permissions:
  FloorIsLava.Staff:
    description: Allows the user to control FIL start-stop-reload-enable-disable.
